[tool.ruff]
line-length = 100
target-version = "py312"
lint.select = ["E", "F", "I"]
lint.ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["crm", "config"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
